## read depth params ##
out_path: "/path/to/NanoRCS/output/procesed_data/05_cna/MRD_setting_cusPoN"  
readCounterScript:  /path/to/envs/hmmcopy/bin/readCounter
chrs:
  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
binSize:  1000000 # set window size to compute coverage

## ichorCNA params ##
ichorCNA_libdir: ../../../ichorCNA
# included in GitHub repo
ichorCNA_rscript:  ../runIchorCNA.R
# use panel matching same bin size (optional)
ichorCNA_normalPanel: ../../inst/extdata/Customized_CYC_PoN_hg19_1Mb.rds_median.rds
# must use gc wig file corresponding to same binSize (required)
ichorCNA_gcWig: ../../inst/extdata/gc_hg19_1000kb.wig
# must use map wig file corresponding to same binSize (required)
ichorCNA_mapWig:  ../../inst/extdata/map_hg19_1000kb.wig
# use bed file if sample has targeted regions, eg. exome data (optional)
ichorCNA_exons:  NULL
ichorCNA_centromere:  ../../inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt
ichorCNA_minMapScore: 0.75
ichorCNA_chrs:  c(1:22)
ichorCNA_fracReadsInChrYForMale: 0.002
ichorCNA_genomeBuild:  hg19
ichorCNA_genomeStyle:  NCBI

# chrs used for training ichorCNA parameters, e.g. tumor fraction. 
ichorCNA_chrTrain:  c(1:22)
# non-tumor fraction parameter restart values; higher values should be included for cfDNA
ichorCNA_normal:  c(0.95,0.99,0.995,0.999)
# ploidy parameter restart values
ichorCNA_ploidy:  c(2)
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  FALSE
ichorCNA_estimateClonality: FALSE
# states to use for subclonal CN
ichorCNA_estimateScPrevalence: FALSE
ichorCNA_scStates:  c()
# set maximum copy number to use
ichorCNA_maxCN:  3
# TRUE/FALSE to include homozygous deletion state
ichorCNA_includeHOMD: FALSE
# Exclude solutions if total length of subclonal CNAs > this fraction of the genome 

###### This has changed
ichorCNA_maxFracGenomeSubclone: 0.3
# Exclude solutions if total length of subclonal CNAs > this fraction of total CNA length
###### This has changed
ichorCNA_maxFracCNASubclone: 0.999
# control segmentation - higher (e.g. 0.9999999) leads to higher specificity and fewer segments
# lower (e.g. 0.99) leads to higher sensitivity and more segments
ichorCNA_txnE:  0.9999
# control segmentation - higher (e.g. 10000000) leads to higher specificity and fewer segments
# lower (e.g. 100) leads to higher sensitivity and more segments
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  pdf
ichorCNA_plotYlim:  c(-2,4)
